### ISSUE TITLE
Aion App not working

### ISSUE THREAD

**Issue by MisplacedSockShell** [ETH-Pantheon/Aion#10]
Hello, 
I'm a total newbie both regarding ethereum and javascript, so I hope I'm not going to any time with this topic. 

I've been trying to use the Aion web app to schedule transactions on the Ropsten network, but I've not been able to. I installed the MetaMask plugin, and I'm holding some Ethereum on the test network, but when I open the [dapp page](https://aion.ethpantheon.com/aionapp.html) I get one of the followings in chrome's javascript console:
- `aionapp.js?v0.007:818 Uncaught TypeError: Cannot read property 'clientAccount' of undefined
    at updateAccountDetails (aionapp.js?v0.007:818)
    at aionapp.js?v0.007:692`
Alongside the "Aion is supported on Mainnet and Ropsten only." alert or
- `Uncaught Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (inpage.js:1)
    at u.validateArgs (inpage.js:1)
    at u.toPayload (inpage.js:1)
    at u.call (inpage.js:1)
    at updateAccountDetails (aionapp.js?v0.007:818)
    at aionapp.js?v0.007:692
`

Refreshing the page multiple times show either of these without any rhyme or reason.
Also the ERC-20 and Advanced buttons are unrensponsive in both cases, and (obviously) I am not able to schedule a transaction.
This behaviour happens on Chrome Version 80.0.3987.132 (Official Build) (64-bit) with exclusively the metamask extension running. 

If this problem can't be fixed is there anothere easy way to schedule a transaction on the Ropsten network? 

Thank you.

**Comment by jfdelgad** [comment]
Hi

The problem seems to be that Metamask is not exposing the accounts by default (that was a breaking change in Metamask). This should be a quick fix, I will be back to you when this is done.

**Comment by jfdelgad** [comment]
Hello,

I have fixed made the corrections required. The issue was with the access to Metamask ethereum provider. the system is up and running in the Mainnet and Ropsten. 

Please let me know if this solved the issue for you completely.

Jaime

**Comment by MisplacedSockShell** [comment]
Tested a bit and everything is perfect, even when inputting big and nonsensical hex numbers in the data section. That's exactly what I needed! Thank you a lot for the quick fix :)
