### ISSUE TITLE
Fees

### ISSUE THREAD

**Issue by mudgen** [ETH-Pantheon/Aion#12]
The [documentation says](https://github.com/ETH-Pantheon/Aion#fees) that fees are 120Gwei (about 2 cents) per transaction.

But that is not about 2 cents per transaction.  120Gwei is worth about $0.000029 which is much less than 2 cents.

Do you mean 120000 Gwei?

Can you please clarify this?

**Comment by jfdelgad** [comment]
You are correct. There is an error in the documentation. The current fee as recorded in the smart contract isis 132000000000000 wei which equals to about 3.2 cents of a USD at the current price of Ether today.
