### ISSUE TITLE
Possible to Run Locally for Testing Purposes?

### ISSUE THREAD

**Issue by zach-is-my-name** [ETH-Pantheon/Aion#15]
I would prefer to test my integration with Aion before deploying (even to Ropsten).  If it is possible, could you offer any general guidance on how to do so?

**Comment by jfdelgad** [comment]
Hello Zach. Unfortunately I do not have right now to write a guide but It is in my agenda. The executor code is in the repository, if you are familiar with js it is possible to make it run after a bit of checking the code. First deploy the smart contract. Then install the executor. You need to specify the ethereum account that the executor will use to send transactions (which should be the same you used to deploy the smart contract), indicate also the http or websockets ethereum provider and that would be all, then just start the executor. 

Let me know if you run into problems.

Recently I deployed Aion in Rinkeby, which is more friendly than ropsten. But I understand if you will prefer to run/test it locally.

**Comment by zach-is-my-name** [comment]
Thanks, that sounds easy enough
