### ISSUE TITLE
How are *very early* calls prevented?

### ISSUE THREAD

**Issue by zach-is-my-name** [ETH-Pantheon/Aion#17]
I'm seeing this here in Aion.sol 
```
    function executeCall(uint256 blocknumber, address from, address to, uint256 value, uint256 gaslimit, uint256 gasprice, uint256 fee, bytes data, uint256 aionId, bool schedType) external {
                          if(schedType) require(blocknumber <= block.timestamp);

```
In English, "require that the schedule block number/time of tx is _less_ than the current block(time)"  

as well as in the executeRequestedTx.js (~ line 19) 

      `  if (web3.utils.toBN(r[i].blocknumber).lte(blocknumber)) { `           

**_I'm wondering how exactly it is enforced that transactions are executed on their scheduled time_** or in the worst case a bit later? Whereas here, they are most likely going to be executed sooner...  

I see that the executor is iterating through the pending tx's conditional on if they exist in the database        
(each of which has an arbitrary execution date attached).    But the executor's **only** criteria whether or not to prep tx and send is the line above, which could be a tx scheduled for 1 minute from now or 1 year from now.  Next it's sent to contract which makes the SAME check before executing... 

I really would like to use this in my project, but with these checks it looks like the transaction will mostly likely be executed sooner than expected, possibly **much sooner** , will it not? What am I missing? Is there a reciprocal constraint that states "don't submit this tx _before_ scheduled block/time" also?

**Comment by zach-is-my-name** [comment]
I just found the Eth Research post and about to dig in...

**Comment by jfdelgad** [comment]
Hi. The line if(schedType) require(blocknumber <= block.timestamp); checks that the call to execute a call is done at a block with time stamp bigger or equal to the one in the schedule request. Therefore if the executor try to execute a scheduled transaction earlier than the indicated by the user, it will fail.

**Comment by zach-is-my-name** [comment]
Wow. Thank you.  I completely misread that.  Seeing` require(currentTime >= scheduledTime)` is WAY more intuitive for me than trying to overcome `require(scheduledTime <= currentTime)`.   Very glad, but embarrassed to have been wrong
