### ISSUE TITLE
Scheduling the execution of a function fail

### ISSUE THREAD

**Issue by ghost** [ETH-Pantheon/Aion#20]
I am using remix with Metamask to deploy Scheduling the execution of a function example on Ropsten Network.

Gas estimation failed
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
execution reverted.

what is the problem? I have not done any changes to the code.

**Comment by jfdelgad** [comment]
Hello. Could you please share the code and the parameters that you are using? Otherwise it is impossible to verify what could be the cause of this reverted execution.

**Comment by ghost** [comment]
pragma solidity ^0.4.24;

// interface Aion
contract Aion {
    uint256 public serviceFee;
    function ScheduleCall(uint256 blocknumber, address to, uint256 value, uint256 gaslimit, uint256 gasprice, bytes data, bool schedType) public payable returns (uint,address);

}

// Main contract
contract MyContract{
    uint256 public sqrtValue;
    Aion aion;

    function schedule_rqsr(uint256 number) public {
        aion = Aion(0xFcFB45679539667f7ed55FA59A15c8Cad73d9a4E);
        bytes memory data = abi.encodeWithSelector(bytes4(keccak256('sqrt(uint256)')),number);
        uint callCost = 200000*1e9 + aion.serviceFee();
        aion.ScheduleCall.value(callCost)( block.number+15, address(this), 0, 200000, 1e9, data, false);
    }

    function sqrt(uint256 number) public {
        sqrtValue = number**2;
    }

    function () public payable {}

}

**Comment by ghost** [comment]
I have just copied the code from git and paste. I am learning so try this for understanding.
The above error comes when I try to execute the **"schedule_rqsr"** function only.

**Comment by jfdelgad** [comment]
You need to be sure to send ether (value) to your contract when deploying it as your contract needs to pay for the aion fees, that are used to pay for the gas of the scheduled transaction.

I deployed the contract above without problem as long as value is sent with the deployment.

**Comment by ghost** [comment]
what value should I enter while deploying?. when I enter 0 then the contract deploys successfully, but when I change the value other than 0 it will show same  error.

**Comment by ghost** [comment]
[screen shot](https://drive.google.com/file/d/1gKIUfb829tD6QLXs6ih3W5utnUXiUi6t/view?usp=sharing)

**Comment by jfdelgad** [comment]
using 0 should trigger the error, any value that is above the fees to be paid should work. I double check this in remix again.

**Comment by Banksy-said-hi** [comment]
I am stuck by the same error. Aion have 3 sample contracts for interacting which all have different purposes. Providing funds while deploying is a must in all of cases?
