### ISSUE TITLE
Transactions do not get executed as i specified

### ISSUE THREAD

**Issue by Banksy-said-hi** [ETH-Pantheon/Aion#22]
Hi

I am trying to interact with Aion smart contract and schedule a transaction. However, after performing ScheduleCall(), although I have specified an address where funds should be sent to, after passing the given time no transferred fund can be seen in the receiver contract. Can you help me to find the issue?

Best

**Comment by Banksy-said-hi** [comment]
I guess this smart contract should be outdated, and there must be some new contracts doing the same by newer versions of solidity.

**Comment by Banksy-said-hi** [comment]
I have tried all the three sample contracts in your README section. None of them perform as intended. Could you please direct me to the right place?

**Comment by jfdelgad** [comment]
This is related to the previous one. Marking solved, please let me know if this need to be reopened.
