### ISSUE TITLE
Aion on Local Blockchain

### ISSUE THREAD

**Issue by Moodai21** [ETH-Pantheon/Aion#8]
Hi, 
I‘m currently developing a local ethereum blockchain. For some parts of my Smart Contracts I Need recursive payments. I found Aion to solve this issue, but all given examples refer to the Main Contract.  As I'm going to develop a local blockchain, it's not possible for me to manage this reference. Could you please tell me, do you have an example of how to implement Aion on local blockchains? Or maybe give me some introductions to do that?
I already found out that I also need the executor, besides the Main Contract...

Thank you for your help!

Best regards,

**Comment by jfdelgad** [comment]
Hi Moodai,
Sorry for the late response.

The solution is to deploy Aion into your blockchain. The smart contract is available in the repository. You will also need to deploy the executor (also in the repository).  You need to install mongodb and indicate the path to access mongo -no need for extra configuration- just pass the path to mongo (see below), the executor will do the rest.

For it to work you need to create a .env file with the following parameters:

aionExecutor_privateKey='put here the private key of the account that will execute the requests'
aionExecutor_aionContractAddress='local address of Aion smart contract'
aionExecutor_httpProvider='your http provider (i.e, infura, localhost:xxxx, etc)'
aionExecutor_dbHost='path to mongo database'
aionExecutor_reqConfirmations='number of confirmations required to accept a request, (i.e, 12)' 

Let me know if this works for you.

Jaime
